# Generated by Django 4.0.1 on 2022-01-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('Individual House', 'Individual House'), ('Apartment', 'Apartment'), ('Gated Comunity', 'Gated Community')], default='Individual House', max_length=50),
        ),
    ]
