# Generated by Django 4.0.1 on 2022-01-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
